### ISSUE TITLE
Resource links are unavailable.

### ISSUE THREAD

**Issue by Neyeee** [nileshkulkarni/relative3d#1]
Hi,

Thank you for the great work.

I tried to deploy the environment and run the codes, but most of the necessary dependent resources seem not downloadable, like all files under 'https://people.eecs.berkeley.edu/~shubhtuls/'.

Besides, there are some small issues like: pip cannot locate PyMesh2 of version 0.2.1 and yyatg (yatg?)

Could you please provide some help with it?  Many thanks.

**Comment by nileshkulkarni** [comment]
Hi, 

I'm sorry for the broken links. For the links that are on the Berkeley page please look [ here](https://github.com/shubhtuls/factored3d/issues/15)

For the issues with pip, if you wish to run the code please remove pymesh from the pip installation. Follow links [here](https://pymesh.readthedocs.io/en/latest/installation.html) to install (You can not install pymesh for now, and things would work. I have updated the condaenv.yml to reflect that)

For yattag please try (the version really does not matter). [here](https://pypi.org/project/yattag/)
``
pip install yattag
``

Thanks,
Nilesh

**Comment by Neyeee** [comment]
Thanks a lot for your instant help.
