### ISSUE TITLE
 Could u share the object files for nyuv2 dataset

### ISSUE THREAD

**Issue by KnightOfTheMoonlight** [nileshkulkarni/relative3d#2]
Hi, Nilesh, Thanks for your work especially for the experiment part. I'm trying to reproduce your work. However, I got stuck in the NYU data part. Specifically, I found the `object_obj` folder of your project is not provided. 
https://github.com/nileshkulkarni/relative3d/blob/15ec79840517e7d67e859ab9f1761a333d43ef9c/data/nyu.py#L99 

After some code checking, I figured out this object mat file names are the same as the work 
``Support Surface Prediction in Indoor Scenes ``  e.g. bed_14.mat. 
However the content of this object is not the same format of your code.
`['surfaces', 'comp', '__version__', '__header__', '__globals__']`

**Comment by KnightOfTheMoonlight** [comment]
Besides, there is no `relative3d.benchmark.nyu` module. But this is not a big issue. By the way which nyu_split do you use, `nyu_split.pkl` or  `nyu_split_correct.pkl`?

**Comment by KnightOfTheMoonlight** [comment]
Hi,  I have checked the data. Still being confused. I think I still need the correct way to get the object data for nyu v2.

From your data, like the `img_xxxx.pkl` , and the nyu v2 object, like `bed_14.mat`, from Support Surface Prediction in Indoor Scenes 
 for the `forward_code()` part of `nyu.py` is:
https://github.com/nileshkulkarni/relative3d/blob/b295cea78b90a900ef17bbfe25266ab5b8b3c4c6/data/nyu.py#L137
`codify_room_data()` part of `nyu_parse.py` is:
https://github.com/nileshkulkarni/relative3d/blob/b295cea78b90a900ef17bbfe25266ab5b8b3c4c6/utils/nyu_parse.py#L111

But the `bed_14.mat` content is as the following, there is not keys required as `voxels`, `scale`, `translation`
```
data
keys
are['imName', 'objects', 'cameraOrigin', 'cameraR', 'cameraK', 'roomR', 'roomOrigin']
data['imName'] is img_5001
data['objects'] is [{'scale': array([0.43092111, 0.72560236, 0.39250373]),
                     'pose_full': array([[-0.25147417, 0.04101868, 0.9669946],
                                         [0.00108675, -0.99908894, 0.04266276],
                                         [0.96786356, 0.01177929, 0.2512006]], dtype=float32),
                     'derekInd': 19, 'bbox': array([1, 355, 65, 425], dtype=uint16),
                     'basemodel': u'chair_42.mat',
                     'trans': array([-1.0238674, 0.7974791, 1.8743548], dtype=float32),
                     'pose_top_view': array([0.96754056, 0., 0.25271583], dtype=float32), 'cls': u'chair'},
                    {'scale': array([0.77087593, 0.70392054, 0.79144216]),
                     'pose_full': array([[0.9669946, 0.04101868, 0.25147417],
                                         [0.04266276, -0.99908894, -0.00108675],
                                         [0.2512006, 0.01177929, -0.96786356]], dtype=float32),
                     'derekInd': 17, 'bbox': array([134, 286, 283, 425], dtype=uint16),
                     'basemodel': u'chair_42.mat',
                     'trans': array([-0.39797106, 0.8451134, 2.814683], dtype=float32),
                     'pose_top_view': array([0.2511266, 0., -0.9679543], dtype=float32), 'cls': u'chair'},
                    {'scale': array([0.26207376, 0.51123041, 0.38800469]),
                     'pose_full': array([[0.9669946, 0.04101868, 0.25147417],
                                         [0.04266276, -0.99908894, -0.00108675],
                                         [0.2512006, 0.01177929, -0.96786356]], dtype=float32),
                     'derekInd': 20, 'bbox': array([1, 329, 43, 355], dtype=uint16),
                     'basemodel': u'table_185.mat',
                     'trans': array([-1.3305825, 0.8972398, 2.3043275], dtype=float32),
                     'pose_top_view': array([0.2511266, 0., -0.9679543], dtype=float32), 'cls': u'table'}]
data['cameraOrigin'] is [0 0 0]
data['cameraR'] is [[0.9669946   0.04101868  0.25147417]
                    [-0.04266276  0.99908894  0.00108675]
[-0.2512006 - 0.01177929
0.96786356]]
data['cameraK'] is [[1.85306393  0.          0.01636589]
                    [0.          1.85524861 - 0.01522798]
[0.
0.
1.]]
data['roomR'] is [[0.9669946   0.04101868  0.25147417]
                  [-0.04266276  0.99908894  0.00108675]
[-0.2512006 - 0.01177929
0.96786356]]
data['roomOrigin'] is [0 0 0]
```

**Comment by nileshkulkarni** [comment]
Hi
Thanks for pointing out the missing file. I updated the [nyu preprocessing file](https://github.com/nileshkulkarni/relative3d/blob/master/docs/preprocess_nyu.md). It has the script to create the mat files that the nyu data loader requires. In summary, that script converts the meshes in NYU to voxels. Since we also need to scale the objects to a unit-cube it also computes a scaling factor and an offset for the translation. Hope that helps!

**Comment by KnightOfTheMoonlight** [comment]
Thanks! Yes!

**Comment by KnightOfTheMoonlight** [comment]
@nileshkulkarni  Hi, Nilesh, I just found from  your paper training details part, you said: 

> In the NYUv2 setting we start with a network trained on the SUNCG dataset and ﬁnetune the network for 16 epochs on the NYU train + val split and evaluate method on the test split.

However from my check, the nyu_split file you offer [here](https://www.dropbox.com/s/mhvu39z1rhqmfox/nyu_splits.tar.gz?dl=0). The file `nyu_split` and `nyu_split_correct` are the same as the following:
```
split_train len is 795
split_test len is 0
split_val len is 654
```

So I guess you use #795 for training, and #654 for testing.

**Comment by KnightOfTheMoonlight** [comment]
Besides, did you train NYUv2 with ground truth bounding box only or with both ground truth bounding boxes and proposals?

**Comment by xiaodongww** [comment]
Hi, thanks for the great job. 

I also have a quick question about NYU dataset. I can not find the meshes of NYU dataset as mentioned here:


> Hi
> Thanks for pointing out the missing file. I updated the [nyu preprocessing file](https://github.com/nileshkulkarni/relative3d/blob/master/docs/preprocess_nyu.md). It has the script to create the mat files that the nyu data loader requires. In summary, that script converts **the meshes in NYU** to voxels. Since we also need to scale the objects to a unit-cube it also computes a scaling factor and an offset for the translation. Hope that helps!

While I am running `python voxelize_objects.py`, it raises an error as follows:
```bash
Traceback (most recent call last):
  File "voxelize_objects.py", line 62, in <module>
    object_ids = [name.replace(".mat","") for name in os.listdir(osp.join(nyu_dir, 'object'))]
OSError: [Errno 2] No such file or directory: '/home/public/workspace/relative3d/nyuv2/object'
```
I think the `object` contains the `meshes of NYU`, but I can not find it. 

I would appreciate any help! 

Thanks in advance.!

@KnightOfTheMoonlight @nileshkulkarni

**Comment by nileshkulkarni** [comment]
@xiaodongww  I was recently helping someone find the meshes. I have uploaded them here for easy access.
https://cmu.box.com/s/4gb25203vltk3maykd9p7mell0gpfjh9

Please run the scripts in preprocess_data/nyu
