### ISSUE TITLE
Missing pretrain model files

### ISSUE THREAD

**Issue by ltindall** [nileshkulkarni/relative3d#3]
Hello, 

It seems like the pretrained model files (*.pth) provided in your cachedir.tar.gz download do not match the names specified in your training examples. I am specifically looking for the ```box3d_base_spatial_mask_common_upsample``` and ```dwr_base_spatial_mask_common_upsample``` specified [here](https://github.com/nileshkulkarni/relative3d/blob/master/docs/training.md#train-on-nyu) for training on NYU. 

Thanks

**Comment by nileshkulkarni** [comment]
I have added the models to the cachedir. Please download the models [here](https://www.dropbox.com/s/r7xw5fw6awj5h4v/cachedir.tar.gz?dl=0).

**Comment by KnightOfTheMoonlight** [comment]
`box3d_base_factored3d_baseline, dwr_base_factored3d_baseline_ft, box3d_base_factored3d_baseline_nyu, dwr_base_factored3d_baseline_ft_nyu`   are missing too. Could you add these model too?
