### ISSUE TITLE
NYU png files

### ISSUE THREAD

**Issue by ltindall** [nileshkulkarni/relative3d#4]
Hello, 

[This line](https://github.com/nileshkulkarni/relative3d/blob/master/data/nyu.py#L122) requires .png image files from the NYUv2 dataset but the website does not provide png files. Where do you get these .png files or how do you generate them?

**Comment by nileshkulkarni** [comment]
yes, it does. I think they are dumped from this [mat file](http://horatio.cs.nyu.edu/mit/silberman/nyu_depth_v2/nyu_depth_v2_labeled.mat) available on the web. Please dump them from here.
