### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by SteveJunGao** [nileshkulkarni/relative3d#7]
Hi,

I'm trying to download the pre-trained model with the provided script:

`wget https://cmu.box.com/s/6bq16zba09rjfezfpflfhepgse0ja9cf`

but it didn't return anything, I'm wondering if this link is broken?  

Thanks

**Comment by samxuxiang** [comment]
You can directly visit https://cmu.box.com/s/6bq16zba09rjfezfpflfhepgse0ja9cf in your brower and download the file.
